# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Webframp
tagline:             ' Ops culture and other hacker ramblings '
description:         ' Another geek with a blog and not much to say. '
url:                 http://webframp.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Sean Escriva
  url:               https://twitter.com/webframp
  email:             sean@escrivas.com

# Custom vars
version:             1.0.0
