# Permalinks
# Use of `relative_permalinks` not supported on github
permalink:           pretty

# Setup
title:               Webframp
tagline:             ' Ops culture and other hacker ramblings '
description:         ' Another geek with a blog and not much to say. '
url:                 http://webframp.com
baseurl:             ""
paginate:            5
exclude:             [Gemfile*, README.md]
include:             ["_pages"]

# Dependencies
gems:
  - jekyll-paginate
  - jekyll-gist

# About/contact
author:
  name:              Sean Escriva
  url:               https://twitter.com/webframp
  email:             sean@escrivas.com

# Custom vars
version:             1.0.0
